=== Noohz/1-DAM/Lenguaje de Marcas/Tema 5/Validacion/xsd/ActividadFinal34XSD.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Declaración del elemento "Pedido" -->
    <xs:element name="pedido">
        
        <xs:complexType>

            <xs:sequence>

                <xs:element name="factura" type="datos_factura"/>
                <xs:element name="articulos" type="datos_articulos"/>

            </xs:sequence>

        </xs:complexType> 

    </xs:element>


    <!-- Declaración "Datos_factura" -->
    <xs:complexType name="datos_factura">

        <xs:sequence>

            <xs:element name="dni" type="xs:string"/>
            <xs:element name="cliente" type="xs:string"/>
            <xs:element name="fecha" type="xs:date"/>
            <xs:element name="dir_entrega" type="datos_entrega"/>

        </xs:sequence>

        <xs:attribute name="pago" type="xs:string"/>

    </xs:complexType>


    <!-- Declaración "Datos_entrega" del elemento "Dir_entrega" -->
    <xs:complexType name="datos_entrega">

        <xs:sequence>

            <xs:element name="direccion" type="xs:string"/>
            <xs:element name="localidad" type="xs:string"/>
            <xs:element name="provincia" type="xs:string"/>

        </xs:sequence>

            <xs:attribute name="cp" type="xs:string"/>

    </xs:complexType>


    <!-- Declaración "Datos_articulos" del elemento "Artículos" -->
    <xs:complexType name="datos_articulos">

        <xs:sequence>

            <xs:element name="articulo" type="datos_articulo" minOccurs="1" maxOccurs="unbounded"/>

        </xs:sequence>

    </xs:complexType> 


    <!-- Declaración "Datos_articulo" del elemento articulo -->
    <xs:complexType name="datos_articulo">

        <xs:sequence>

            <xs:element name="unidades" type="xs:decimal"/>
            <xs:element name="precio" type="xs:decimal"/>

        </xs:sequence>

        <xs:attribute name="codigo" type="xs:string"/>

    </xs:complexType>

</xs:schema>

=== Noohz/1-DAM/Lenguaje de Marcas/Tema 5/Validacion/xsd/ActividadFinal34XML.xml
<?xml version="1.0" encoding="UTF-8"?>

<pedido xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="/home/diurno/Escritorio/html%20Lenguaje%20de%20Marcas/Tema%205/Validacion/xsd/ActividadFinal34XSD.xsd">

    <factura pago="Transferencia bancaria">

        <dni>12345678A</dni>
        <cliente>Rafael Nadal Perera</cliente>
        <fecha>2020-01-31</fecha>
        <dir_entrega cp="10004">

            <direccion>C/ La Paz</direccion>
            <localidad>Cáceres</localidad>
            <provincia>Cáceres</provincia>

        </dir_entrega>

    </factura>


    <articulos>

        <articulo codigo="aaa-111">

            <unidades>8</unidades>
            <precio>23.94</precio>

        </articulo>

        <articulo codigo="BBB-222">

            <unidades>15</unidades>
            <precio>29.04</precio>

        </articulo>

    </articulos>

</pedido>
