=== Noohz/1-DAM/Lenguaje de Marcas/Tema 5/Validacion/xsd/DefinicionDatoCompuestoXSD.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="pelicula">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="titulo" type="xs:string"/>
            <xs:element name="datos" type="datos_peli"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:complexType name="datos_peli">
    <xs:sequence>
        <xs:element name="director" type="xs:string"/>
        <xs:element name="estreno" type="xs:decimal"/>
        <xs:element name="actor" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

</xs:schema>

=== Noohz/1-DAM/Lenguaje de Marcas/Tema 5/Validacion/xsd/DefinicionDatoCompuestoXML.xml
<?xml version="1.0" encoding="UTF-8" ?>

<pelicula xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="/home/diurno/Escritorio/html Lenguaje de Marcas/Tema 5/Validacion/xsd/DefinicionDatoCompuestoXSD.xsd">

    <titulo>Piratas del Caribe:La Maldici√≥n de la Perla Negra</titulo>
    <datos>
        <director>Gore Verbinski</director>
        <estreno>2003</estreno>
        <actor>Johnny Depp</actor>
        <actor>Keira Knightley</actor>
        <actor>Orlando Bloom</actor>
    </datos>
</pelicula>
