=== Noohz/1-DAM/Lenguaje de Marcas/Tema 5/Validacion/xsd/Ejercicio1XSD.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="catalogo" type="datos_catalogo"/>

    <!-- Definición del tipo datos_catalogo -->

    <xs:complexType name="datos_catalogo">

        <xs:sequence>

            <xs:element name="articulo" type="datos_articulo" minOccurs="1" maxOccurs="unbounded"/>

        </xs:sequence>

    </xs:complexType>

    <!-- Definición del tipo datos_articulo -->

    <xs:complexType name="datos_articulo">

        <xs:sequence>

            <xs:element name="codigo" type="datos_articulo"/>
            <xs:element name="nombre" type="datos_articulo"/>
            <xs:element name="precio" type="datos_articulo"/>
            <xs:element name="provincia" type="datos_articulo"/>

        </xs:sequence>

    </xs:complexType>

</xs:schema>

=== Noohz/1-DAM/Lenguaje de Marcas/Tema 5/Validacion/xsd/Ejercicio1.xml
<?xml version="1.0" encoding="UTF-8"?>

<catalogo xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="./Ejercicio1XSD.xsd">

    <articulo>

        <codigo>aBc-012</codigo>
        <nombre>Torta del Casar</nombre>
        <precio>11.75</precio>
        <provincia>Caceres</provincia>

    </articulo>

    <articulo>

        <codigo>Xyz-789</codigo>
        <nombre>Queso de la Serena</nombre>
        <precio>10.50</precio>
        <provincia>Badajoz</provincia>

    </articulo>

</catalogo>
