=== Noohz/1-DAM/Lenguaje de Marcas/Tema 5/Validacion/xsd/EjercicioFinalDefinicionDatosXSD.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="alumnos">

        <xs:complexType>
            
            <xs:sequence>

                <xs:element name="alumno" type="datos_alumno" minOccurs="1" maxOccurs="unbounded"/>

            </xs:sequence>

        </xs:complexType>  

    </xs:element>


    <!-- Definici贸n del tipo datos_alumno -->

    <xs:complexType name="datos_alumno">

        <xs:sequence>

            <xs:element name="nombre" type="xs:string"/>
            <xs:element name="apellidos" type="xs:string"/>
            <xs:element name="direccion" type="datos_direccion"/>
            <xs:element name="contactar" type="datos_contactar"/>

        </xs:sequence>

    </xs:complexType>

    <!-- Definici贸n del tipo datos_direcci贸n -->
    
    <xs:complexType name="datos_direccion">

        <xs:sequence>

            <xs:element name="domicilio" type="xs:string"/>
            <xs:element name="codigo_postal" type="xs:integer"/>
            <xs:element name="localidad" type="xs:string"/>
            <xs:element name="provincia" type="xs:string"/>

        </xs:sequence>

    </xs:complexType>


    <!-- Definici贸n del tipo datos_contactar -->

    <xs:complexType name="datos_contactar">

        <xs:sequence>

            <xs:element name="telf_casa" type="xs:integer"/>
            <xs:element name="telf_movil" type="xs:integer"/>
            <xs:element name="telf_trabajo" type="xs:integer"/>
            <xs:element name="telf_trabajo" type="xs:integer"/>
            <xs:element name="email" type="xs:string"/>

        </xs:sequence>

    </xs:complexType>

</xs:schema>

=== Noohz/1-DAM/Lenguaje de Marcas/Tema 5/Validacion/xsd/EjercicioFinalDefinicionDatosXML.xml
<?xml version="1.0" encoding="UTF-8"?>

<alumnos xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="/home/diurno/Escritorio/html%20Lenguaje%20de%20Marcas/Tema%205/Validacion/xsd/EjercicioFinalDefinicionDatosXSD.xsd">

    <alumno>

        <nombre>Rafael</nombre>
        <apellidos>Nadal</apellidos>

        <direccion>

            <domicilio>C/ Ancha</domicilio>
            <codigo_postal>10004</codigo_postal>
            <localidad>Cáceres</localidad>
            <provincia>Cáceres</provincia>

        </direccion>

        <contactar>

            <telf_casa>927242424</telf_casa>
            <telf_movil>64444444</telf_movil>
            <telf_trabajo>927111111</telf_trabajo>
            <telf_trabajo>927222222</telf_trabajo>
            <email>rafael@gmail.com</email>

        </contactar>

    </alumno>

    <alumno>

        <nombre>Fernando</nombre>
        <apellidos>Alonso Díaz</apellidos>

        <direccion>

            <domicilio>C/ Victoria</domicilio>
            <codigo_postal>10033</codigo_postal>
            <localidad>Cáceres</localidad>
            <provincia>Cáceres</provincia>

        </direccion>

        <contactar>

            <telf_casa>927252525</telf_casa>
            <telf_movil>644555555</telf_movil>
            <telf_trabajo>927333333</telf_trabajo>
            <telf_trabajo>927444444</telf_trabajo>
            <email>fernando@gmail.com</email>

        </contactar>

    </alumno>

</alumnos>
